server:
  port: 8023
spring:
  application:
    name: ZUUL-GATEWAY
zuul:
  ignored-services: "*"
  prefix: "/services"
  routes:
    plat:
      path: /plat/**
      service-id: easygo-plat
    product:
      path: /product/**
      service-id: easygo-product
ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000