server:
  port: 8023
spring:
  application:
    name: ZUUL-GATEWAY
zuul:
  routes:
    myPlat.serviceId: EASYGO-PLAT
    myPlat.path: /plat/**
    myProduct.serviceId: EASYGO-PRODUCT
    myProduct.path: /product/**
  ignored-services: "*"
  prefix: "/services"