server:
  port: 8004
spring:
  application:
    name: easygo-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easygo_product
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:cn/easygo/mall/product/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.easygo.domain,cn.itsource.easygo.query

