server:
  port: 8001
spring:
  application:
    name: easygo-plat
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easygo?useSSL=false
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:cn/itsource/easygo/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.easygo.domain